### ISSUE TITLE
[Eclipse 549118] Windows 10: Container Shell is not working in the Codewind plugin for Eclips

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind-eclipse#112] opened 2019-06-26 19:26 UTC
**Environment:**
- **Codewind version:** Latest Development Version (codewind-0.2.0-201906261508.zip)
- **Eclipse version:** 2019-06 (4.12.0)
- **OS:** VM with Windows 10

**Description:**
Container Shell is not working in the Codewind plugin for Eclipse.

![Screen Shot 2019-06-26 at 3 08 33 PM 1](https://user-images.githubusercontent.com/49531960/60208513-758f1000-9826-11e9-96a7-0aca503ff51f.png)

**Steps:**
1. Install and start the Codewind plugin for Eclipse
2. Create a project
3. Right click on the created project
4. Click on "Open Container Shell"

@jagraj

**Comment by eharris369** [comment] 2019-06-26 19:43
It works fine on Linux and MAC.  The problem is with Eclipse.  I can create the same shell using the Eclipse preferences and it has the same behaviour.  It is actually working but the text is not showing up for some reason.  I tried switching to dark mode and other modes but it didn't help.

**Comment by eharris369** [comment] 2019-07-09 19:07
I have opened the following eclipse bug:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=549118

**Comment by eharris369** [comment] 2019-08-15 16:55
I have found a workaround.  After the terminal comes up and you can see the cursor, type _clear_ and this will reset the terminal.  It works after that.

**Comment by jagraj** [comment] 2019-08-19 11:59
I am on eclipse 2019-06 release and I no longer see this issue on my windows VM. Could you please verify once.?

Earlier I had to type some command to get the data on the screen from the container shell window.

![Screen Shot 2019-08-19 at 7 57 27 AM](https://user-images.githubusercontent.com/713849/63263630-1f9f7d00-c257-11e9-8d7a-e5ec7fd3e34e.png)

**Comment by eharris369** [comment] 2020-01-22 20:46
Closing as nobody is able to reproduce this problem anymore. I also closed the Eclipse bug.

**Closed by eharris369** 2020-01-22 20:46 UTC
