### ISSUE TITLE
Plugin does not handle missing docker images gracefully

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind-eclipse#225] opened 2019-08-22 09:24 UTC
Attempting to recreate https://github.com/eclipse/codewind/issues/222, so same environment as there.

I installed the Codewind Eclipse plugin using 'Install new software' with the install site being https://download.eclipse.org/codewind/codewind-eclipse/master/latest/repository/
Codewind installed and I double-clicked to start. I then got the following error message in a pop-up:

```
'Starting Codewind' has encountered a problem.
There was a problem trying to start Codewind: Debug: false
==> created file installer-docker-compose.yaml
==> environment structure written to installer-docker-compose.yaml
System architecture is:  amd64
Host operating system is:  windows
Attempting to find available port
Port 10000 Available
Please wait whilst containers initialize...  
Pulling codewind-performance (codewind-performance-amd64:0.3)...
The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]pull access denied for codewind-performance-amd64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
==> finished deleting file installer-docker-compose.yaml
```
I believe this is caused because the plugin believes because it's a 0.3 plugin, it should be pulling codewind images tagged 0.3, which do not exist in Docker hub yet as they have not been released. The error message displayed is confusing to the end user and needs to be handled in a more user-friendly way.

**Comment by tetchel** [comment] 2019-08-22 17:54
This is the intended behaviour; you have to export `INSTALL_VERSION=latest` in your environment while we are in this shutdown period where the 0.3 images don't exist yet.

I'm closing this because there isn't a way for the plugin to recover from this and an end user will never see this message

**Closed by tetchel** 2019-08-22 17:54 UTC

**Comment by mattcolegate** [comment] 2019-08-22 20:34
@tetchel Could not the plugin respond to this by defaulting to the `latest` tag?
Otherwise, fair enough if it's expected behaviour.

**Comment by tetchel** [comment] 2019-08-22 20:35
The thing is, if the plugin expects 0.2 but gets `latest` it will be working against a different version of the APIs then it is expecting, which will lead to undefined behaviour
