### ISSUE TITLE
Projects in codewind workspace folder and in eclipse tools does not match

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind-eclipse#105] opened 2019-06-26 05:40 UTC
While creating multiple projects from eclipse tools, the number of projects in the eclipse codewind explorer view does not match with codewind workspace folder.

This should be fixed for the upcoming milestone driver, please add stopship tag.

Here are the logs and screenshots from the failure.

[.log](https://github.com/eclipse/codewind-eclipse/files/3328367/default.log)

![TARGET_DIR_NOT_EMPTY](https://user-images.githubusercontent.com/713849/60153677-088e6280-97b3-11e9-9f94-422656f8f47d.JPG)

![image](https://user-images.githubusercontent.com/713849/60153752-383d6a80-97b3-11e9-953f-14d1d102ec5f.png)

**Comment by eharris369** [comment] 2019-06-26 13:11
Can you please describe exactly what you did to get into this situation?  The message coming from PFE is that it can't create the project because the folder already exists.  If the IDE gets an error from PFE on project create then it does not import the project into Eclipse.  Did you try to create the project once and it did not show up so you tried to create it again with the same name?

**Comment by eharris369** [comment] 2019-06-26 13:15
I cannot reproduce this.  I created 10 projects in a row and everything was fine.  Please provide more information or close the issue.

**Comment by eharris369** [comment] 2019-06-26 13:25
@jagraj Did this occur after the read timeouts described in #104?

**Comment by jagraj** [comment] 2019-06-26 14:19
Hi Erin, 
yes this happened after read timeouts. It did not refresh with the projects created, I did refresh manually and still shows only two projects in the workspace.

I am wondering why other projects in my workspace not showing up in this list.?
May be codewind issue.?


```
[
  {
    "projectID": "2bd34000-97cf-11e9-bc9a-87cd60213eab",
    "name": "go1906win",
    "codewindVersion": "latest",
    "language": "go",
    "host": "172.20.0.4",
    "ports": {
      "exposedPort": "32768",
      "internalPort": "8000"
    },
    "applicationPort": "",
    "workspace": "/C/codewind-workspace/",
    "directory": "go1906win",
    "infLockFlag": false,
    "locOnDisk": "/codewind-workspace/go1906win",
    "loadTestPath": "/codewind-workspace/go1906win/load-test",
    "projectType": "docker",
    "buildLogPath": "/codewind-workspace/.logs/go1906win-2bd34000-97cf-11e9-bc9a-87cd60213eab/docker.build.log",
    "state": "open",
    "autoBuild": true,
    "buildStatus": "success",
    "detailedBuildStatus": " ",
    "ignoredPaths": [
      "/.project",
      "*/node_modules*",
      "*/.git/*",
      "*/.DS_Store",
      "*/*.swp",
      "*/*.swx",
      "*/4913",
      "*/.dockerignore",
      "*/.gitignore",
      "*/*~",
      "/.settings"
    ],
    "metricsAvailable": false,
    "projectWatchStateId": "eea336ecb6f57d8fd0ccdc9322406c79",
    "logs": {
      "build": {
        "origin": "workspace",
        "files": [
          "/codewind-workspace/.logs/go1906win-2bd34000-97cf-11e9-bc9a-87cd60213eab/docker.build.log"
        ]
      },
      "app": {
        "origin": "workspace",
        "files": [
          "/codewind-workspace/.logs/go1906win-2bd34000-97cf-11e9-bc9a-87cd60213eab/app.log"
        ]
      }
    },
    "appStatus": "started",
    "lastbuild": 1561525209594,
    "appImageLastBuild": "1561525209594",
    "location": "/codewind-workspace/go1906win",
    "validationStatus": "success",
    "validationResults": [],
    "containerId": "f85b90dc9b7d869a7ccbf958fac7789cdbdcd849b773738adb72b6fc4954b13c",
    "detailedAppStatus": "The project path that file watcher pings is /health or /"
  },
  {
    "projectID": "8f06c200-97cf-11e9-bc9a-87cd60213eab",
    "name": "java1906win",
    "codewindVersion": "latest",
    "language": "java",
    "host": "172.20.0.5",
    "ports": {
      "exposedPort": "32770",
      "internalPort": "9080",
      "internalDebugPort": "7777"
    },
    "applicationPort": "",
    "workspace": "/C/codewind-workspace/",
    "directory": "java1906win",
    "infLockFlag": false,
    "locOnDisk": "/codewind-workspace/java1906win",
    "loadTestPath": "/codewind-workspace/java1906win/load-test",
    "startMode": "run",
    "projectType": "liberty",
    "buildLogPath": "/codewind-workspace/.logs/java1906win-8f06c200-97cf-11e9-bc9a-87cd60213eab/docker.build.log",
    "state": "open",
    "autoBuild": true,
    "buildStatus": "success",
    "detailedBuildStatus": " ",
    "ignoredPaths": [
      "/.project",
      "/Dockerfile-tools",
      "/target",
      "/mc-target",
      "/cli-config.yml",
      "/README.md",
      "/Jenkinsfile",
      "/.cfignore",
      "*/node_modules*",
      "*/.git/*",
      "*/.DS_Store",
      "*/*.swp",
      "*/*.swx",
      "*/4913",
      "*/.dockerignore",
      "*/.gitignore",
      "*/*~",
      "/.settings",
      "/chart"
    ],
    "projectWatchStateId": "b2a2025e15a525de9c375d1f3325ccdf",
    "metricsAvailable": true,
    "appStatus": "started",
    "appImageLastBuild": "1561525625163",
    "logs": {
      "build": {
        "origin": "workspace",
        "files": [
          "/codewind-workspace/.logs/java1906win-8f06c200-97cf-11e9-bc9a-87cd60213eab/maven.build.log",
          "/codewind-workspace/.logs/java1906win-8f06c200-97cf-11e9-bc9a-87cd60213eab/docker.build.log"
        ]
      },
      "app": {
        "origin": "container",
        "files": [
          "/codewind-workspace/.logs/java1906win-8f06c200-97cf-11e9-bc9a-87cd60213eab/app.log",
          "/tmp/liberty/liberty/wlp/usr/servers/defaultServer/logs/console.log",
          "/tmp/liberty/liberty/wlp/usr/servers/defaultServer/logs/messages.log"
        ],
        "dir": "/codewind-workspace/java1906win/mc-target/liberty/wlp/usr/servers/defaultServer/logs/ffdc"
      }
    },
    "lastbuild": 1561525690416,
    "location": "/codewind-workspace/java1906win",
    "operation": {
      "operationId": "68c1be75825d6a0b4891c62efdc5fab1",
      "type": "validate",
      "projectInfo": {
        "projectType": "liberty",
        "location": "/codewind-workspace/java1906win",
        "projectID": "8f06c200-97cf-11e9-bc9a-87cd60213eab"
      }
    },
    "validationStatus": "success",
    "validationResults": [],
    "detailedAppStatus": "The project path that file watcher pings is /health or /",
    "containerId": "cb80a46920ce2dee1293cc098b240b1ffb3b96c47d7ed2b5c69fa711baccf6ee"
  }
]
```

**Comment by eharris369** [comment] 2019-06-26 14:42
An issue has been opened against PFE for this.

**Closed by eharris369** 2019-06-26 14:42 UTC
Labels: bug, stopship
