### ISSUE TITLE
[Windows 10] Performance Monitor window does not open in Eclipse, but it does in the browser

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind-eclipse#114] opened 2019-06-26 20:01 UTC
**Environment:**
- **Codewind version:** Latest Development Version (codewind-0.2.0-201906261508.zip)
- **Eclipse version:** 2019-06 (4.12.0)
- **OS:** VM with Windows 10

**Description:**
Performance Monitor window does not open in Eclipse, but it does in the browser.

![Screen Shot 2019-06-26 at 3 36 10 PM](https://user-images.githubusercontent.com/49531960/60210324-9f4a3600-982a-11e9-9b39-2dc41badb081.png)

![Screen Shot 2019-06-26 at 3 40 34 PM](https://user-images.githubusercontent.com/49531960/60210331-a2ddbd00-982a-11e9-820f-937b911e5735.png)

**Steps:**
1. Install and start the Codewind plugin for Eclipse
2. Create a project (i.e. Java MicroProfile)
3. Right click on the created project
4. Click on "Open Performance Monitor"

@jagraj

**Comment by eharris369** [comment] 2019-06-26 20:12
This is a duplicate of #111

**Closed by eharris369** 2019-06-26 20:12 UTC
